name: Run Playwright and Generate a video, screenshots, and LightHouse HTML Report

on:
  push:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --cpus 2 --memory 4G --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libgbm-dev chromium-bsu
          npm ci
          npx playwright install chromium
          npm install -g lighthouse chrome-launcher axe-core chromium wait-on
          npx playwright install-deps  
          npm run build --turbo

      - name: Start the application
        run: |
          export DISPLAY=:1
          npm run start 2>&1 > app.log &
          npx wait-on --timeout 30000 http://localhost:3000 || (cat app.log && exit 1)

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.js

      - name: Upload report, screenshots and videos of failed tests
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
